[package]
name = "arch-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
serde_derive = "1.0.228"
arch_client = { path = "./arch-client" }
serde_json = "1.0.149"
serde = "1.0.228"
tokio = { version = "1.49.0", features = ["full"] }
